version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/starters/angular/ai-chatbot"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/starters/angular/ai-text-editor"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/starters/angular/basic"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/starters/angular/dashboard"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/starters/angular/ecommerce"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/starters/angular/image-gallery"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/starters/angular/kanban"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/starters/nextjs/basic"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/starters/nextjs/firebase-ecommerce"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/starters/nextjs/shopify-ecommerce"
    schedule:
      interval: "weekly"
